import Providers from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Appbar from "@/components/Appbar";
import { ThemeProvider } from "@/components/theme-provider";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "tt",
  description: "Generated by create next app",
};

export default async function RootLayout() {
  const session = await getServerSession();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className="container py-10 mx-auto">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Providers>
              <Appbar />
            </Providers>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
