import Providers from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Appbar from "@/components/Appbar";
import { ThemeProvider } from "@/components/theme-provider";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "tt",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="container py-10 mx-auto">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <SessionProvider session={session}>
              <Appbar />
            </SessionProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
